### PR TITLE
Task.unpoll title bar#7

### PR DESCRIPTION
**Pull request by Jack-Pham**

### CODE REVIEW

**Comment by ddfridley** [comment]
@Jack-Pham this looks great! But I have realized that the back arrow and redo button need to do something.

New properties for the component:
- [ ] onBackButton function that is called when someone clicks on the back button
- [ ] onRedoButton function that is called when someone clicks on the redo button
- [ ] backActive must be true or the button is not active, and is grayed out.
- [ ] redoActive must be true or the button is not active, and it is grayed out
Also
- [ ]  cursor should change to pointer over those icons, when it is active.

If you have other ideas how to do these properties/parameters, i'm open. 

Extra credit if you can figure out how to make a story book use case for the onBackButton or onRedoButton - but not required at this point.

**Comment by ddfridley** [comment]
@Jack-Pham when I run storybook with this, and change currentStep nothing happens.  I know this worked before.  
Also, instead of putting console.info into the component, you should pass in a function - onBackButton from the story and then have that function do the console.info.  Then we can test the component, and higher level code can figure out what to do when the back button is pressed. 

I'm going to be on vacation, coming back on Wednesday.  I won't try to have a wednesday call, but you want to talk one night or day after that - tell me when. 

Thanks!

**Comment by Jack-Pham** [comment]
@ddfridley I just come back from vacation so I didn't have much time to work on it. I'll take a look and let's you know.

**Review by ddfridley — APPROVED** [review]
I separated out NavBar and Title because it seemed like two different things.  There could be a super component that combines them if that ends up making sense.

I took the state out of navbar and made it stateless - we will have to resolve what back button and redo button do at a higher level 

I also added a way of showing backButton clicks and redoButton clicks into the story.

**Pull request merged**
